### ISSUE TITLE
git push fails

### ISSUE THREAD

**Issue by Jonyorker** [karlludwigweise/git-subtree#1]
Hi,

I came across your action.

What I am hoping to accomplish is to pull in a repo in a pull request, add that commit and have the repo included when the pull request is merged.

Currently, I am running into an issue with the push step

```
Run git push
  git push
  shell: /usr/bin/bash -e {0}
fatal: You are not currently on a branch.
To push the history leading to the current (detached HEAD)
state now, use

    git push origin HEAD:<name-of-remote-branch>
```
    
This is my current action script

```
name: Pipeline action

on:
  pull_request:
    branches:
    - main

jobs:
  add-common:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: karlludwigweise/git-subtree@v1
        with:
          pat: ${{ secrets.PAT }}
          repo: https://github.com/somerepo.git
          position: master
          action: add
          prefix: reponame
          message: Pull in reponame
      - name: push
        run: git push
```
